### ISSUE TITLE
Quick question about the evaluation results of AIGCDetectBenchmark

### ISSUE THREAD

**Issue by Megum1** [chuangchuangtan/NPR-DeepfakeDetection#10]
Hi,

Great appreciation for your interesting work!

Just wondering whether the results in the AIGCDetectBenchmark are measured in AP or accuracy?

**Comment by chuangchuangtan** [comment]
The Acc. and A.P. results on AIGCDetectBenchmark are as follows:

====== ==================
                  AIGCDetect_testset
====== ==================
2024_06_26_06_33_32
(0 wukong      ) acc: 91.7; ap: 98.9
(1 stable_diffusion_v_1_5) acc: 97.5; ap: 99.6
(2 stargan     ) acc: 99.6; ap: 100.0
(3 gaugan      ) acc: 85.4; ap: 88.7
(4 stylegan    ) acc: 96.1; ap: 99.9
(5 stylegan2   ) acc: 98.1; ap: 100.0
(6 whichfaceisreal) acc: 60.7; ap: 94.0
(7 DALLE2      ) acc: 99.6; ap: 100.0
(8 biggan      ) acc: 87.3; ap: 94.0
(9 progan      ) acc: 99.9; ap: 100.0
(10 Glide       ) acc: 96.7; ap: 99.6
(11 ADM         ) acc: 84.9; ap: 98.3
(12 cyclegan    ) acc: 90.3; ap: 99.1
(13 Midjourney  ) acc: 92.6; ap: 99.0
(14 stable_diffusion_v_1_4) acc: 97.4; ap: 99.7
(15 VQDM        ) acc: 90.1; ap: 99.2
(16 Mean      ) acc: 91.7; ap: 98.1
