### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by ggamaz** [chuangchuangtan/NPR-DeepfakeDetection#11]
Thanks for your great work sincerely! I wonder what's the difference between the NPR.pth and model_epoch_last_3090.pth，I want to load the NPR.pth, but there is an error, which looks like about model structure, i donot know how to do
![image](https://github.com/chuangchuangtan/NPR-DeepfakeDetection/assets/103712346/75f2f857-87f9-4fc4-8603-25acd5f353d1)

**Comment by chuangchuangtan** [comment]
You can load pre-trained models in the following ways:
```
try:
    model.load_state_dict(torch.load(opt.model_path, map_location='cpu'), strict=True)
except:
    from collections import OrderedDict
    from copy import deepcopy
    state_dict = torch.load(opt.model_path, map_location='cpu')['model']
    pretrained_dict = OrderedDict()
    for ki in state_dict.keys():
        pretrained_dict[ki[7:]] = deepcopy(state_dict[ki])
    model.load_state_dict(pretrained_dict, strict=True)
```
