### ISSUE TITLE
The testing results using the provided weights are quite different from the paper.

### ISSUE THREAD

**Issue by githuboflk** [chuangchuangtan/NPR-DeepfakeDetection#17]
For example, the GauGAN in Table 1 : Acc 82.5 vs 86.6.
![NPR](https://github.com/user-attachments/assets/15e2c2b4-6309-4251-a92b-6d8c14cb0795)

**Comment by githuboflk** [comment]
The results in Table 5 are basically consistent with the paper.  This discrepancy between the results of the different tables puzzled me a bit.

**Comment by chuangchuangtan** [comment]
Please use our [Python environment](https://drive.google.com/file/d/16MK7KnPebBZx5yeN6jqJ49k7VWbEYQPr/view)  for testing.

**Comment by Tuesdayo** [comment]
> Please use our [Python environment](https://drive.google.com/file/d/16MK7KnPebBZx5yeN6jqJ49k7VWbEYQPr/view) for testing.

Thank you for your reply and outstanding contribution.
