### ISSUE TITLE
Cross GAN sources evaluation on the Self synthesis 10 GANs datasets | problem in results replication

### ISSUE THREAD

**Issue by barcavia** [chuangchuangtan/NPR-DeepfakeDetection#2]
Hi, when I evaluate your NPR.pth checkpoint on the 10 GANs from self-synthesis, I get the following results:

*************************
(0 AttGAN    ) acc: 83.0; ap: 96.2
(1 BEGAN     ) acc: 50.1; ap: 50.1
(2 CramerGAN ) acc: 52.4; ap: 53.0
(3 GANimation) acc: 50.0; ap: 50.2
(4 InfoMaxGAN) acc: 52.4; ap: 53.0
(5 MMDGAN    ) acc: 52.4; ap: 53.0
(6 RelGAN    ) acc: 99.6; ap: 100.0
(7 S3GAN     ) acc: 79.0; ap: 80.1
(8 SNGAN     ) acc: 52.4; ap: 53.0
(9 STGAN     ) acc: 50.2; ap: 51.5
Mean:  acc: 62.2; ap: 64.0
*************************

as you can see, only the AttnGAN, RelGAN and S3GAN were replicated perfectly (compared to the results reported in the paper). the other GANs are way too far..
Perhaps the issue lies with the GANGen-Detection dataset you uploaded.

**Comment by chuangchuangtan** [comment]
#1
