### ISSUE TITLE
question about 4-classes training setting

### ISSUE THREAD

**Issue by YinqiCai** [chuangchuangtan/NPR-DeepfakeDetection#6]
Hi, , thanks for your great work!
But I have a confusing question: What's the meaning of 4-classes training setting mentioned in the paper? I found it seems to be 2-classes(real/fake) training setting in the code.

**Comment by chuangchuangtan** [comment]
The term "4-classes training setting" refers to the amount of data in the training set. The training set of [CNNDetection](https://github.com/peterwang512/CNNDetection) contains 20 classes of images, with fake images generated by ProGAN and real images sampled from the [LSUN dataset](http://dl.yf.io/lsun/objects/). [The Official  ProGAN code](https://github.com/tkarras/progressive_growing_of_gans) release the [pretrained models](https://drive.google.com/drive/folders/15hvzxt_XxuokSmj0uO4xxMTMWVc0cIMU?usp=drive_link) on LSUN dataset.

**Comment by YinqiCai** [comment]
I get it, thank you very much!

**Comment by chandlerbing65nm** [comment]
Just to clarify: during training, the classification remains binary (real vs. fake), but you only use four classes (car, cat, chair, and horse) instead of the available twenty classes? can you tell what was the reason for this?
